environment:
  global:
    CIBW_SKIP: pp* *ppc64le *aarch64 *s390x *win_arm64
    CIBW_PRERELEASE_PYTHONS: False

    CIBW_TEST_COMMAND: "pytest {project}/test"
    CIBW_TEST_REQUIRES: pytest numpy
    
    # test error in musllinux
    # buliding numpy for test takes too long time for cp310-win*
    CIBW_TEST_SKIP: cp310-win* cp*musllinux_*

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-bigsur
      APPVEYOR_JOB_NAME: "python37-macos-bigsur-1"
      CIBW_BUILD: cp311-macosx_x86_64
      OSX_ARCHITECTURES: x86_64
      CIBW_CMD_OPTION: --archs x86_64
      CIBW_VERSION: 2.11.2
      PYBIND11_BRANCH: stable

    - APPVEYOR_BUILD_WORKER_IMAGE: macos-bigsur
      APPVEYOR_JOB_NAME: "python37-macos-bigsur-1-arm"
      CIBW_BUILD: cp311-macosx_arm64
      OSX_ARCHITECTURES: arm64
      CIBW_CMD_OPTION: --archs arm64
      CIBW_VERSION: 2.11.2
      PYBIND11_BRANCH: stable

    - APPVEYOR_BUILD_WORKER_IMAGE: macos-bigsur
      APPVEYOR_JOB_NAME: "python37-macos-bigsur-2"
      CIBW_BUILD: cp38-macosx_universal2 cp39-macosx_universal2 cp310-macosx_universal2
      OSX_ARCHITECTURES: universal2
      CIBW_CMD_OPTION: --archs universal2
      CIBW_VERSION: 2.2.2
      PYBIND11_BRANCH: stable

    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      APPVEYOR_JOB_NAME: "python37-macos-mojave-3"
      CIBW_BUILD: cp36-macosx_x86_64 cp37-macosx_x86_64
      CIBW_CMD_OPTION:
      CIBW_VERSION: 2.2.2
      OSX_ARCHITECTURES: x86_64
      PYBIND11_BRANCH: stable

    # - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
    #   APPVEYOR_JOB_NAME: "python37-macos-mojave-1"
    #   CIBW_BUILD: cp27-* cp35-*
    #   CIBW_CMD_OPTION:
    #   CIBW_VERSION: 1.5.5
    #   OSX_ARCHITECTURES: x86_64
    #   PYBIND11_BRANCH: v2.5

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      APPVEYOR_JOB_NAME: "python37-vs2017-2"
      CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-* 
      CIBW_VERSION: 2.2.2
      PYBIND11_BRANCH: stable

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      APPVEYOR_JOB_NAME: "python37-vs2017-3"
      CIBW_BUILD: cp311-win_amd64 cp311-win32
      CIBW_VERSION: 2.11.2
      PYBIND11_BRANCH: stable

    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   APPVEYOR_JOB_NAME: "python37-vs2015-1"
    #   CIBW_BUILD: cp27-* cp35-*
    #   CIBW_VERSION: 1.5.5
    #   PYBIND11_BRANCH: stable

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-ubuntu-1"
      CIBW_BUILD: cp27-* cp35-*
      CIBW_CMD_OPTION:
      CIBW_VERSION: 1.5.5
      PYBIND11_BRANCH: v2.5

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-ubuntu-2"
      CIBW_BUILD: cp36-* cp37-*
      CIBW_CMD_OPTION:
      CIBW_VERSION: 2.2.2
      PYBIND11_BRANCH: v2.5

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-ubuntu-3"
      CIBW_BUILD: cp38-* cp39-*
      CIBW_CMD_OPTION:
      CIBW_VERSION: 2.2.2
      PYBIND11_BRANCH: stable

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-ubuntu-4"
      CIBW_BUILD: cp310-*
      CIBW_CMD_OPTION:
      CIBW_VERSION: 2.2.2
      PYBIND11_BRANCH: stable

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-ubuntu-5"
      CIBW_BUILD: cp311-*
      CIBW_CMD_OPTION:
      CIBW_VERSION: 2.11.2
      PYBIND11_BRANCH: stable

stack: python 3.8

init:
  - cmd: set PATH=C:\Python38;C:\Python38\Scripts;%PATH%

install:
  - git submodule update --init --recursive

build_script:
  - cmd: cd src\ext\pybind11
  - cmd: git checkout %PYBIND11_BRANCH%
  - cmd: cd ..\..\..
  - cmd: c:\python38\python -m pip install -U pip
  - cmd: c:\python38\python -m pip install cibuildwheel==%CIBW_VERSION%
  - cmd: c:\python38\python -m cibuildwheel --output-dir wheelhouse

  - sh: cd src/ext/pybind11
  - sh: git checkout $PYBIND11_BRANCH
  - sh: cd ../../..
  - sh: python -m pip install -U pip
  - sh: python -m pip install cibuildwheel==$CIBW_VERSION
  - sh: set OSX_ARCHITECTURES=$OSX_ARCHITECTURES
  - sh: python -m cibuildwheel $CIBW_CMD_OPTION --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
