# appveyor.yml
---
environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

build_script:
- python setup.py bdist_wheel

install:
- pip install tox

test_script:
- tox

artifacts:
  - path: dist\*
