# appveyor.yml

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.x"
    PYTHON_ARCH: "32"
    TOXENV: "py27"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PYTHON: "C:\\Python27-x64"
    PYTHON_VERSION: "2.7.x"
    PYTHON_ARCH: "64"
    TOXENV: "py27"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PYTHON: "C:\\Python36"
    PYTHON_VERSION: "3.6.x"
    PYTHON_ARCH: "32"
    TOXENV: "py36"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PYTHON: "C:\\Python36-x86"
    PYTHON_VERSION: "3.6.x"
    PYTHON_ARCH: "64"
    TOXENV: "py36"
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
build_script:
  - pip install wheel
  - python setup.py bdist_wheel
test_script:
  - pip install tox
  - tox -e %TOXENV%
artifacts:
- path: dist/*