environment:
  global:
    CIBW_TEST_COMMAND: "pytest {project}/test"
    # CIBW_TEST_REQUIRES: pytest numpy pillow # pillow installation failed in python 3.10
    CIBW_TEST_REQUIRES: pytest numpy
    CIBW_SKIP: pp* *ppc64le *aarch64 *s390x *arm64 *universal2
    CIBW_PRERELEASE_PYTHONS: False

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      APPVEYOR_JOB_NAME: "python37-x64-vs2015"

stack: python 3.7

init:
- cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install:
- git submodule update --init --recursive

build_script:
- python -m pip install cibuildwheel==1.12.0
- python -m cibuildwheel --output-dir wheelhouse
- python -m pip install -U cibuildwheel==2.2.0
- python -m cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
